@ContactMS_HostAddress = https://localhost:7298

GET {{ContactMS_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ContactMS_HostAddress}}/api/contact/CreateContact
Content-Type: application/json

{
  "Name":"test",
  "ActiveStatus":1,
  "CreatedUserId":1
}

###

GET {{ContactMS_HostAddress}}/api/contact/GetContactById/6

###

POST {{ContactMS_HostAddress}}/api/contact/EditContact
Content-Type: application/json

{
  "Id":1,
  "Name":"test",
  "ActiveStatus":1,
  "EditedUserId":1
}

###

POST {{ContactMS_HostAddress}}/api/contactdetail/CreateContactDetail
Content-Type: application/json

{
  "ContactNumber":"123456",
  "ContactId":1,
  "CreatedUserId":1
}

###

POST {{ContactMS_HostAddress}}/api/contactdetail/EditContactDetail
Content-Type: application/json

{
  "Id":1,
  "ContactNumber":"1234567",
  "ContactId":1,
  "EditedUserId":1
}

###
GET {{ContactMS_HostAddress}}/api/contactdetail/GetContactDetailById/6

###

POST {{ContactMS_HostAddress}}/api/contact/CreateContactWithDetails
Content-Type: application/json

{
  "Name":"abcde",
  "ActiveStatus":1,
  "CreatedUserId":1,
  "ContactDetails":
  
     [
        {
          "ContactNumber":"12345"
        },
        {
          "ContactNumber":"1234"
        }
     ]
   
  
}

###
